Change moose profile and create a build log

diff --git a/docker/moose-ubuntu/Dockerfile b/docker/moose-ubuntu/Dockerfile
--- a/docker/moose-ubuntu/Dockerfile
+++ b/docker/moose-ubuntu/Dockerfile
@@ -9,7 +9,7 @@ COPY ./scripts/setup-python-venv.sh /home/scripts
 COPY ./scripts/build-moose.sh /home/scripts
 
 # Set up python environment
-RUN ./scripts/setup-python-venv.sh -w /home -d env -e moose -i /home/env/ubuntu-envs.sh -o /home/.moose_base_profile
+RUN ./scripts/setup-python-venv.sh -w /home -d env -e moose -i /home/env/ubuntu-envs.sh -o /home/env/moose_base_profile
 
 # Optional build-arg to specify moose version and cores
 ARG moose_tag=
@@ -17,4 +17,4 @@ ARG moose_git_sha=
 ARG compile_cores=4
 
 # Build MOOSE
-RUN ./scripts/build-moose.sh -w /home -j "$compile_cores" -t "$moose_tag" -s "$moose_git_sha" -d /usr/lib/x86_64-linux-gnu/hdf5/serial/ -e /home/.moose_base_profile  -o /home/.moose_profile -f "" -r
+RUN ./scripts/build-moose.sh -w /home -j "$compile_cores" -t "$moose_tag" -s "$moose_git_sha" -d /usr/lib/x86_64-linux-gnu/hdf5/serial/ -e /home/env/moose_base_profile  -o /home/env.moose_profile -f "" -r > /home/build_moose.log 2>&1 && "Succeeding in building moose" || echo "Failed to build MOOSE"
